estoque/ext/db/models.py
# -*- encoding: utf-8 -*-
# begin
from estoque.ext.db import db


class Address(db.Model):
    __tablename__ = "address"
    id = db.Column("id", db.Integer, primary_key=True)
    zip = db.Column("zip", db.Unicode)
    country = db.Column("country", db.Unicode)
    address = db.Column("address", db.Unicode)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    user = db.relationship("User", foreign_keys=user_id)


class Brands(db.Model):
    __tablename__ = "brands"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    category_id = db.Column(
        "category_id", db.Integer, db.ForeignKey("category.id")
    )

    user = db.relationship("User", foreign_keys=user_id)
    # server como referecia reversa.
    category = db.relationship("Category", foreign_keys=category_id)


class Category(db.Model):
    __tablename__ = "category"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode, unique=True)
    on_menu = db.Column("on_menu", db.Boolean)


class Items(db.Model):
    __tablename__ = "items"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode)
    image = db.Column("image", db.Unicode)
    price = db.Column("price", db.BigInteger)
    brands_id = db.Column("brands_id", db.Integer, db.ForeignKey("brands.id"))
    available = db.Column("available", db.Boolean)
    stock = db.Column("stock", db.Integer)

    brands = db.relationship("Brands", foreign_keys=brands_id)


class Order(db.Model):
    __tablename__ = "order"
    id = db.Column("id", db.Integer, primary_key=True)
    created_at = db.Column("created_at", db.DateTime)
    completed = db.Column("completed", db.Boolean)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    brands_id = db.Column("brands_id", db.Integer, db.ForeignKey("brands.id"))
    address_id = db.Column(
        "address_id", db.Integer, db.ForeignKey("address.id")
    )

    user = db.relationship("User", foreign_keys=user_id)
    brands = db.relationship("Brands", foreign_keys=brands_id)
    address = db.relationship("Address", foreign_keys=address_id)


class OrderItems(db.Model):
    __tablename__ = "order_items"
    order_id = db.Column("order_id", db.Integer, db.ForeignKey("order.id"))
    items_id = db.Column("items_id", db.Integer, db.ForeignKey("items.id"))
    qtd = db.Column("qtd", db.Integer)
    id = db.Column("id", db.Integer, primary_key=True)

    order = db.relationship("Order", foreign_keys=order_id)
    items = db.relationship("Items", foreign_keys=items_id)


class Checkout(db.Model):
    __tablename__ = "checkout"
    id = db.Column("id", db.Integer, primary_key=True)
    payment = db.Column("payment", db.Unicode)
    total = db.Column("total", db.BigInteger)
    created_at = db.Column("created_at", db.DateTime)
    completed = db.Column("completed", db.Boolean)
    order_id = db.Column("order_id", db.Integer, db.ForeignKey("order.id"))

    order = db.relationship("Order", foreign_keys=order_id)


# end

estoque/app.py
from flask import Flask

from estoque.ext import (
    admin,
    auth,
    cli,
    config,
    db,
    hooks,
    migrate,
    site,
    toolbar,
)


def create_app():
    app = Flask(__name__)
    config.init_app(app)
    db.init_app(app)
    auth.init_app(app)
    admin.init_app(app)
    migrate.init_app(app)
    cli.init_app(app)
    toolbar.init_app(app)
    site.init_app(app)
    hooks.init_app(app)
    return app

estoque/ext/admin/__init__.py
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from estoque.ext.db import db
from estoque.ext.db.models import Category, Brands, Items

admin = Admin()


def init_app(app):
    admin.name = app.config.get("APPNAME", "Estoque Online")
    admin.template_mode = app.config.get("ADMIN_TEMPLATE_MODE", "bootstrap2")
    admin.init_app(app)


    admin.add_view(ModelView(Category, db.session))
    admin.add_view(ModelView(Brands, db.session))
    admin.add_view(ModelView(Items, db.session))

estoque/ext/cli/__init__.py
import click
from estoque.ext.db import db
from estoque.ext.db import models  # noqa


def init_app(app):

    @app.cli.command()
    def create_db():
        """Este comando inicializa o DB"""
        db.create_all()

    @app.cli.command()
    def listar_pedidos():
        click.echo("lista de pedidos")

estoque/ext/config/__init__.py
from dynaconf import FlaskDynaconf


def init_app(app):
    FlaskDynaconf(app)

estoque/ext/db/__init__.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def init_app(app):
    db.init_app(app)

estoque/ext/site/__init__.py
from .main import bp


def init_app(app):
    app.register_blueprint(bp)

estoque/ext/site/controllers.py
def get_all_active_brands():
    """Get all brands"""

estoque/ext/site/main.py
from flask import render_template
from flask import Blueprint
from flask import current_app

bp = Blueprint("site", __name__)


@bp.route("/")
def index():
    current_app.logger.debug("Entrei na Home")
    return render_template("index.html")


@bp.route("/sobre")
def about():
    return render_template("about.html")


@bp.route("/marcas")
def brands():
    return render_template("brands.html")

estoque/ext/toolbar/__init__.py
from flask_debugtoolbar import DebugToolbarExtension


def init_app(app):
    DebugToolbarExtension(app)

estoque/templates/about.html
{% extends "base.html"%}

{% block top %}
<section class="hero is-primary">
    <div class="hero-body">
      <h1>Loja Online</h1>
    </div>
  </section>
{% endblock top %}

{% block main %}
    <p>
        Construindo o Tcc
    </p>
{% endblock main %}

estoque/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Loja Online</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <!-- Importando o Normalize -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" 
        integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />

        
    <!-- Importando CSS -->
    <link rel="stylesheet" href="/estoque/static/css/global.css">
    <link rel="stylesheet" href="/estoque/static/css/top.css">


    <!-- Importando Fontes -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    
    {% endblock head %}

    {% block extra_css %} {% endblock extra_css %}

</head>
  <body>
    {% block nav %}
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <strong> Tcc Loja Online</strong>
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="/">
              Inicio
            </a>
      
            <a class="navbar-item" href="{{ url_for('site.brands')}}">
              Marcas
            </a>

            <a class="navbar-item" href="{{ url_for('site.about')}}">
              Sobre
            </a>
      
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Opções
              </a>
      
              <div class="navbar-dropdown">
                <a class="navbar-item">
                  Dvd's
                </a>
                <a class="navbar-item">
                  Alto Falantes
                </a>
                <a class="navbar-item">
                  Componentes
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item">
                  Report an issue
                </a>
              </div>
            </div>
          </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-primary">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light">
                  Log in
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
      {% endblock nav %}


      {% block top %} {% endblock top %}
      

  <section class="section">
    <div class="container">
        {% block main %} {% endblock main %}
    </div>
  </section>

  {% block footer %}
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>
  {% endblock footer %}

  <!-- Nosso JS -->
  <script src="/estoque/static/js/main.js"></script>

  </body>
</html>

estoque/templates/brands.html
{% extends "base.html" %}
{% import "macros/list_item.html" as list_item %}

    {% block top %}
    <section class="hero is-primary">
        <div class="hero-body">
          <p class="title">
            {{ site_name }}
          </p>
          <p class="subtitle">
            {{ site_subtitle }}
          </p>
        </div>
      </section>
      {% endblock top %}

      {% block main %}
        <div class="columns"  style="display: grid; grid-template-columns: 1fr 1fr 1fr;">
          
          {{ list_item.cards([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) }}
         
          </div>
          {% endblock main %}
       

estoque/templates/index.html
{% extends "base.html" %}
{% import "macros/list_item.html" as list_item %}

    {% block top %}
    <section class="hero is-primary">
        <div class="hero-body">
          <p class="title">
            {{ site_name }}
          </p>
          <p class="subtitle">
            {{ site_subtitle }}
          </p>
        </div>
      </section>
      {% endblock top %}

      {% block main %}
        <div class="columns" style="display: grid; grid-template-columns: 1fr 1fr 1fr;">
            {{ list_item.cards([1, 2, 3, 4, 5, 6]) }}
        </div>
      {% endblock main %}
       

estoque/templates/macros/list_item.html
{% macro cards(items) %}

{% for item in items %}
<div class="column">
  
    <div class="card">
        <div class="card-image">
          <figure class="image is-4by3">
            <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4">John Smith</p>
              <p class="subtitle is-6">@johnsmith</p>
            </div>
          </div>
      
          <div class="content">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Phasellus nec iaculis mauris. <a>@bulmaio</a>.
            <a href="#">#css</a> <a href="#">#responsive</a>
            <br>
            <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
          </div>
        </div>
      </div>

</div>
{% endfor %}

{% endmacro %}